### PR TITLE
fix zombie process

### PR DESCRIPTION
**Pull request by javitorl**
fix issue #22

### CODE REVIEW

**Comment by pnicolai** [comment]
:+1:

**Comment by i90rr** [comment]
If incron gets eventually forked I will be interested in continue following the fork; if possible please let me know :)

**Comment by UnitedMarsupials** [comment]
This needs a rework as suggested in #40. The current implementation will block until the child process returns. @ericjunkermann's suggestion seems much better -- we ignore the status code anyway.

Of course, we only worry about this to begin with because we install a `SIGCHLD`-handler -- is it really necessary to drain the pipes leading to the already-exited child?

Anyway, here is my implementation based Eric's proposal (but following the existing coding style): 196975d26fd04176a1c877fa3c404efd8103c9c2 (the 08d8e7a should be reverted).

**Comment by ar-** [comment]
Hi @UnitedMarsupials . I agree with the change. But just for the form, could you be so kind and create a new pull request that reverts 08d8e7a and puts your change in place. I'd like to keep a clear track of history and contributions.

**Comment by UnitedMarsupials** [comment]
Once you merge the #41, I will be able to create a new one easily. Until then Github wants to combine all my commits into one PR, which is unsightly...

**Pull request merged**
