### PR TITLE
Fix zombies without blocking too much

### PR DESCRIPTION
**Pull request by UnitedMarsupials-zz**

### CODE REVIEW

**Comment by UnitedMarsupials** [comment]
This reverts #23 and addresses #40...

**Comment by ar-** [comment]
This closes #40 and fixes #22 .

**Comment by ar-** [comment]
Thanks for the quick work. :+1:

**Comment by Slamdunk** [comment]
@ar- this needs to land into upstream distros, may you tag a new version please?
It's 4 years now without a tag, and zombie processes still are an issue on Debian 10 :cry:

**Comment by dpvpro** [comment]
Please, please, bump new version 5.13

**Pull request merged**
